# Generated by Django 5.2.4 on 2025-07-15 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='uploads/')),
                ('status', models.CharField(choices=[('Investigation', 'Investigation'), ('Under Trial', 'Under Trial'), ('Case Closed', 'Case Closed'), ('Referred to Court', 'Referred to Court'), ('Other Relevant Status', 'Other Relevant Status')], default='Investigation', max_length=30)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
